//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChitChat.Server.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public Post()
        {
            this.Comments = new HashSet<Comment>();
            this.PostSecurities = new HashSet<PostSecurity>();
            this.Likes = new HashSet<Like>();
        }
    
        public int ID { get; set; }
        public int UserID { get; set; }
        public int CatID { get; set; }
        public string Body { get; set; }
        public System.DateTime Created { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<PostSecurity> PostSecurities { get; set; }
        public virtual ICollection<Like> Likes { get; set; }
    }
}
