CREATE TABLE [dbo].[Like]
(
	[ID] INT NOT NULL IDENTITY(1,1) PRIMARY KEY, 
    [UserID] INT NOT NULL, 
    [PostID] INT NOT NULL, 
    CONSTRAINT [FK_Like_User] FOREIGN KEY (UserID) REFERENCES [User](ID),
    CONSTRAINT [FK_Like_Post] FOREIGN KEY (PostID) REFERENCES Post(ID)
)
